# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
pod 'Firebase/Core', '~> 6.3.0'

target 'medproject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for medproject

  target 'medproject-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

    pod 'react-native-checkbox', :path => '../node_modules/@react-native-community/checkbox'

    pod 'react-native-maps', :path => '../node_modules/react-native-maps'

    pod 'RNDateTimePicker', :path => '../node_modules/@react-native-community/datetimepicker'

    pod 'react-native-sms', :path => '../node_modules/react-native-sms'

    pod 'react-native-camera', :path => '../node_modules/react-native-camera'

    pod 'RNFS', :path => '../node_modules/react-native-fs'

    pod 'react-native-document-picker', :path => '../node_modules/react-native-document-picker'

    pod 'RNAudio', :path => '../node_modules/react-native-audio'

    pod 'RNSound', :path => '../node_modules/react-native-sound'

    pod 'RNAudioRecord', :path => '../node_modules/react-native-audio-record'

    pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'

  end

  target 'medprojectTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'medproject-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for medproject-tvOS

end
